
import React from 'react';
import type { AppDefinition, FileSystemItem } from './types';
import { 
    FileExplorerIcon, SettingsIcon, TaskManagerIcon, FolderIcon, TextFileIcon, PictureIcon,
    NotepadIcon, PaintIcon, SnippingToolIcon, ToDoIcon, ClockIcon, VideoFileIcon, AudioFileIcon, PDFFileIcon, YouTubeIcon, EdgeIcon,
    CalculatorIcon, TerminalIcon, StoreIcon, WeatherIcon, MineIcon, GameControllerIcon, FacebookIcon, TwitterIcon, InstagramIcon, LinkedInIcon, RedditIcon, PinterestIcon, TikTokIcon, NetflixIcon, SpotifyIcon, TwitchIcon, GoogleDriveIcon, DropboxIcon, TrelloIcon, SlackIcon, NotionIcon, FigmaIcon, CanvaIcon, WikipediaIcon, AmazonIcon, DiscordIcon, GitHubIcon, DocumentIcon, SpreadsheetIcon, PresentationIcon, Microsoft365Icon, StackOverflowIcon, GiphyIcon, SoundCloudIcon, IMDbIcon, CodePenIcon, NYTimesIcon, EbayIcon, DuolingoIcon, GoogleMapsIcon, UnsplashIcon
} from './assets/icons';
import FileExplorer from './apps/FileExplorer';
import Settings from './apps/Settings';
import TaskManager from './apps/TaskManager';
import ImageViewer from './apps/ImageViewer';
import Notepad from './apps/Notepad';
import Paint from './apps/Paint';
import SnippingTool from './apps/SnippingTool';
import ToDo from './apps/ToDo';
import Clock from './apps/Clock';
import VideoAudioPlayer from './apps/VideoAudioPlayer';
import PDFViewer from './apps/PDFViewer';
import Browser from './apps/Browser';
import Calculator from './apps/Calculator';
import Terminal from './apps/Terminal';
import Store from './apps/Store';
import Weather from './apps/Weather';
import Minesweeper from './apps/Minesweeper';
import GamePlayer from './apps/GamePlayer';
import { GAMES_LIST } from './apps/games';

// Dynamically create game definitions from the central list
const gameDefinitions = GAMES_LIST.reduce((acc, game) => {
    acc[game.id] = {
        id: game.id,
        name: game.name,
        icon: <GameControllerIcon className="w-6 h-6 text-purple-400" />,
        component: GamePlayer,
        baseData: { 
            url: game.url,
            name: game.name,
        },
        storeCategory: 'game',
        imageUrl: game.imageUrl,
        publisher: game.publisher,
        rating: game.rating,
        ratingCount: game.ratingCount,
        category: game.category,
        description: game.description,
        screenshots: game.screenshots,
        features: game.features,
        releaseDate: game.releaseDate,
        lastUpdated: game.lastUpdated,
        systemRequirements: game.systemRequirements,
        reviewSummary: game.reviewSummary,
        reviewTags: game.reviewTags,
    };
    return acc;
}, {} as { [key: string]: AppDefinition });

const WEB_APP_DEFINITIONS: { [key: string]: AppDefinition } = {
    // Social
    'facebook': { id: 'facebook', name: 'Facebook', icon: <FacebookIcon className="w-6 h-6 text-[#1877F2]" />, component: Browser, baseData: { url: 'https://www.facebook.com' }, storeCategory: 'app', publisher: 'Meta', category: 'Social' },
    'twitter': { id: 'twitter', name: 'X (Twitter)', icon: <TwitterIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.twitter.com' }, storeCategory: 'app', publisher: 'X Corp.', category: 'Social' },
    'instagram': { id: 'instagram', name: 'Instagram', icon: <InstagramIcon className="w-6 h-6 text-[#E4405F]" />, component: Browser, baseData: { url: 'https://www.instagram.com' }, storeCategory: 'app', publisher: 'Meta', category: 'Social' },
    'linkedin': { id: 'linkedin', name: 'LinkedIn', icon: <LinkedInIcon className="w-6 h-6 text-[#0A66C2]" />, component: Browser, baseData: { url: 'https://www.linkedin.com' }, storeCategory: 'app', publisher: 'Microsoft', category: 'Social' },
    'reddit': { id: 'reddit', name: 'Reddit', icon: <RedditIcon className="w-6 h-6 text-[#FF4500]" />, component: Browser, baseData: { url: 'https://www.reddit.com' }, storeCategory: 'app', publisher: 'Reddit, Inc.', category: 'Social' },
    'pinterest': { id: 'pinterest', name: 'Pinterest', icon: <PinterestIcon className="w-6 h-6 text-[#E60023]" />, component: Browser, baseData: { url: 'https://www.pinterest.com' }, storeCategory: 'app', publisher: 'Pinterest, Inc.', category: 'Social' },
    'tiktok': { id: 'tiktok', name: 'TikTok', icon: <TikTokIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.tiktok.com' }, storeCategory: 'app', publisher: 'ByteDance', category: 'Social' },
    'discord': { id: 'discord', name: 'Discord', icon: <DiscordIcon className="w-6 h-6 text-[#5865F2]" />, component: Browser, baseData: { url: 'https://discord.com/app' }, storeCategory: 'app', publisher: 'Discord Inc.', category: 'Social' },
    // Entertainment
    'netflix': { id: 'netflix', name: 'Netflix', icon: <NetflixIcon className="w-6 h-6 text-[#E50914]" />, component: Browser, baseData: { url: 'https://www.netflix.com' }, storeCategory: 'app', publisher: 'Netflix, Inc.', category: 'Entertainment' },
    'spotify': { id: 'spotify', name: 'Spotify', icon: <SpotifyIcon className="w-6 h-6 text-[#1DB954]" />, component: Browser, baseData: { url: 'https://open.spotify.com' }, storeCategory: 'app', publisher: 'Spotify AB', category: 'Entertainment' },
    'twitch': { id: 'twitch', name: 'Twitch', icon: <TwitchIcon className="w-6 h-6 text-[#9146FF]" />, component: Browser, baseData: { url: 'https://www.twitch.tv' }, storeCategory: 'app', publisher: 'Amazon', category: 'Entertainment' },
    'soundcloud': { id: 'soundcloud', name: 'SoundCloud', icon: <SoundCloudIcon className="w-6 h-6 text-[#FF5500]" />, component: Browser, baseData: { url: 'https://soundcloud.com' }, storeCategory: 'app', publisher: 'SoundCloud', category: 'Entertainment' },
    'imdb': { id: 'imdb', name: 'IMDb', icon: <IMDbIcon className="w-6 h-6 text-[#F5C518]" />, component: Browser, baseData: { url: 'https://www.imdb.com' }, storeCategory: 'app', publisher: 'Amazon', category: 'Entertainment' },
    'giphy': { id: 'giphy', name: 'Giphy', icon: <GiphyIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://giphy.com' }, storeCategory: 'app', publisher: 'Giphy, Inc.', category: 'Entertainment' },
    // Productivity
    'google-drive': { id: 'google-drive', name: 'Google Drive', icon: <GoogleDriveIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://drive.google.com' }, storeCategory: 'app', publisher: 'Google', category: 'Productivity' },
    'dropbox': { id: 'dropbox', name: 'Dropbox', icon: <DropboxIcon className="w-6 h-6 text-[#0061FF]" />, component: Browser, baseData: { url: 'https://www.dropbox.com' }, storeCategory: 'app', publisher: 'Dropbox, Inc.', category: 'Productivity' },
    'trello': { id: 'trello', name: 'Trello', icon: <TrelloIcon className="w-6 h-6 text-[#0079BF]" />, component: Browser, baseData: { url: 'https://trello.com' }, storeCategory: 'app', publisher: 'Atlassian', category: 'Productivity' },
    'slack': { id: 'slack', name: 'Slack', icon: <SlackIcon className="w-6 h-6 text-[#4A154B]" />, component: Browser, baseData: { url: 'https://slack.com' }, storeCategory: 'app', publisher: 'Salesforce', category: 'Productivity' },
    'notion': { id: 'notion', name: 'Notion', icon: <NotionIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.notion.so' }, storeCategory: 'app', publisher: 'Notion Labs, Inc.', category: 'Productivity' },
    'figma': { id: 'figma', name: 'Figma', icon: <FigmaIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.figma.com' }, storeCategory: 'app', publisher: 'Figma, Inc.', category: 'Creativity' },
    'canva': { id: 'canva', name: 'Canva', icon: <CanvaIcon className="w-6 h-6 text-[#00C4CC]" />, component: Browser, baseData: { url: 'https://www.canva.com' }, storeCategory: 'app', publisher: 'Canva', category: 'Creativity' },
    'microsoft365': { id: 'microsoft365', name: 'Microsoft 365', icon: <Microsoft365Icon className="w-6 h-6 text-[#D83B01]" />, component: Browser, baseData: { url: 'https://www.office.com' }, storeCategory: 'app', publisher: 'Microsoft', category: 'Productivity' },
    'google-docs': { id: 'google-docs', name: 'Google Docs', icon: <DocumentIcon className="w-6 h-6 text-[#4285F4]" />, component: Browser, baseData: { url: 'https://docs.google.com' }, storeCategory: 'app', publisher: 'Google', category: 'Productivity' },
    'google-sheets': { id: 'google-sheets', name: 'Google Sheets', icon: <SpreadsheetIcon className="w-6 h-6 text-[#0F9D58]" />, component: Browser, baseData: { url: 'https://sheets.google.com' }, storeCategory: 'app', publisher: 'Google', category: 'Productivity' },
    'google-slides': { id: 'google-slides', name: 'Google Slides', icon: <PresentationIcon className="w-6 h-6 text-[#F4B400]" />, component: Browser, baseData: { url: 'https://slides.google.com' }, storeCategory: 'app', publisher: 'Google', category: 'Productivity' },
    // Developer
    'github': { id: 'github', name: 'GitHub', icon: <GitHubIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://github.com' }, storeCategory: 'app', publisher: 'GitHub, Inc.', category: 'Developer Tools' },
    'stackoverflow': { id: 'stackoverflow', name: 'Stack Overflow', icon: <StackOverflowIcon className="w-6 h-6 text-[#F48024]" />, component: Browser, baseData: { url: 'https://stackoverflow.com' }, storeCategory: 'app', publisher: 'Stack Exchange', category: 'Developer Tools' },
    'codepen': { id: 'codepen', name: 'CodePen', icon: <CodePenIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://codepen.io' }, storeCategory: 'app', publisher: 'CodePen, Inc.', category: 'Developer Tools' },
    // News & Reference
    'wikipedia': { id: 'wikipedia', name: 'Wikipedia', icon: <WikipediaIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.wikipedia.org' }, storeCategory: 'app', publisher: 'Wikimedia Foundation', category: 'Reference' },
    'nytimes': { id: 'nytimes', name: 'The New York Times', icon: <NYTimesIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.nytimes.com' }, storeCategory: 'app', publisher: 'The New York Times Company', category: 'News' },
    'duolingo': { id: 'duolingo', name: 'Duolingo', icon: <DuolingoIcon className="w-6 h-6 text-[#58CC02]" />, component: Browser, baseData: { url: 'https://www.duolingo.com' }, storeCategory: 'app', publisher: 'Duolingo, Inc.', category: 'Education' },
    // Shopping
    'amazon': { id: 'amazon', name: 'Amazon', icon: <AmazonIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.amazon.com' }, storeCategory: 'app', publisher: 'Amazon.com, Inc.', category: 'Shopping' },
    'ebay': { id: 'ebay', name: 'eBay', icon: <EbayIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://www.ebay.com' }, storeCategory: 'app', publisher: 'eBay Inc.', category: 'Shopping' },
    // Other
    'google-maps': { id: 'google-maps', name: 'Google Maps', icon: <GoogleMapsIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://maps.google.com' }, storeCategory: 'app', publisher: 'Google', category: 'Utility' },
    'unsplash': { id: 'unsplash', name: 'Unsplash', icon: <UnsplashIcon className="w-6 h-6" />, component: Browser, baseData: { url: 'https://unsplash.com' }, storeCategory: 'app', publisher: 'Unsplash', category: 'Photos' },
};


export const APP_DEFINITIONS: { [key: string]: AppDefinition } = {
    'file-explorer': {
        id: 'file-explorer',
        name: 'File Explorer',
        icon: <FileExplorerIcon className="w-6 h-6 text-yellow-500" />,
        component: FileExplorer,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.2,
        ratingCount: '1.1k',
        category: 'Utility',
        description: 'Manage your files and folders, navigate your system, and organize your digital life with the classic Windows File Explorer.',
        screenshots: ['https://i.imgur.com/8Q6o5mS.png', 'https://i.imgur.com/UdiCVUn.png'],
        features: ['Tabbed interface', 'Quick Access panel', 'Detailed file views', 'Context-sensitive menus'],
        releaseDate: '10/05/2021',
        lastUpdated: '05/20/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'Users appreciate the familiar interface and powerful file management capabilities.',
        reviewTags: ['Familiar', 'Powerful', 'Organized'],
    },
    'settings': {
        id: 'settings',
        name: 'Settings',
        icon: <SettingsIcon className="w-6 h-6 text-gray-400" />,
        component: Settings,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.0,
        ratingCount: '890',
        category: 'Utility',
        description: 'Customize your experience, manage system settings, and personalize your device to your liking.',
        screenshots: ['https://i.imgur.com/UdiCVUn.png'],
        features: ['Personalization options', 'Network management', 'Device settings', 'Account management'],
        releaseDate: '10/05/2021',
        lastUpdated: '06/01/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A central hub for all system configurations, making it easy to tailor the OS.',
        reviewTags: ['Customizable', 'Centralized', 'Easy to use'],
    },
    'task-manager': {
        id: 'task-manager',
        name: 'Task Manager',
        icon: <TaskManagerIcon className="w-6 h-6 text-blue-400" />,
        component: TaskManager,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.6,
        ratingCount: '2.3k',
        category: 'Utility',
        description: 'Monitor running applications and processes, check system performance, and manage startup apps.',
        screenshots: ['https://i.imgur.com/uC22iN0.png'],
        features: ['Process monitoring', 'Performance graphs', 'App history', 'Startup management'],
        releaseDate: '10/05/2021',
        lastUpdated: '04/15/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'Essential tool for power users to manage system resources and troubleshoot issues.',
        reviewTags: ['Powerful', 'Detailed', 'Essential'],
    },
    'image-viewer': {
        id: 'image-viewer',
        name: 'Image Viewer',
        icon: <PictureIcon className="w-6 h-6" />,
        component: ImageViewer,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 3.8,
        ratingCount: '500',
        category: 'Photos',
        description: 'A simple and fast image viewer for all your favorite photos and images.',
        screenshots: ['https://i.imgur.com/Gz7kY8A.png'],
        features: ['Supports multiple formats', 'Lightweight and fast', 'Simple navigation'],
        releaseDate: '10/05/2021',
        lastUpdated: '01/10/2023',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A quick and easy way to view images without extra bloat.',
        reviewTags: ['Fast', 'Simple', 'Lightweight'],
    },
    'notepad': {
        id: 'notepad',
        name: 'Notepad',
        icon: <NotepadIcon className="w-6 h-6 text-white" />,
        component: Notepad,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.8,
        ratingCount: '10k',
        category: 'Productivity',
        description: 'The classic, lightweight text editor for simple notes and code. No frills, just pure text editing power.',
        screenshots: ['https://i.imgur.com/y8g8eW5.png'],
        features: ['Plain text editing', 'Save and open files', 'Simple interface', 'Fast performance'],
        releaseDate: '10/05/2021',
        lastUpdated: '03/22/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'The quintessential text editor. Praised for its simplicity and speed.',
        reviewTags: ['Classic', 'Simple', 'Reliable'],
    },
    'paint': {
        id: 'paint',
        name: 'Paint',
        icon: <PaintIcon className="w-6 h-6 text-red-400" />,
        component: Paint,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.1,
        ratingCount: '3.1k',
        category: 'Creativity',
        description: 'Unleash your creativity with this simple yet powerful drawing and image editing tool.',
        screenshots: ['https://i.imgur.com/pZJ4YvB.png'],
        features: ['Basic drawing tools', 'Color palette', 'Eraser function', 'Save as PNG'],
        releaseDate: '10/05/2021',
        lastUpdated: '02/18/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A fun and easy-to-use tool for quick sketches and simple edits.',
        reviewTags: ['Creative', 'Fun', 'Simple'],
    },
    'snipping-tool': {
        id: 'snipping-tool',
        name: 'Snipping Tool',
        icon: <SnippingToolIcon className="w-6 h-6 text-gray-300" />,
        component: SnippingTool,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.5,
        ratingCount: '1.5k',
        category: 'Utility',
        description: 'Quickly capture screenshots of your entire screen or a specific area with this handy utility.',
        screenshots: ['https://i.imgur.com/Xq5wJ9b.png'],
        features: ['Rectangular snip', 'Saves to desktop', 'Easy to use overlay'],
        releaseDate: '10/05/2021',
        lastUpdated: '11/30/2023',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A very useful utility for capturing and sharing screen content quickly.',
        reviewTags: ['Useful', 'Quick', 'Convenient'],
    },
    'todo': {
        id: 'todo',
        name: 'To Do',
        icon: <ToDoIcon className="w-6 h-6 text-blue-300" />,
        component: ToDo,
        storeCategory: 'app',
        publisher: 'Open Source',
        rating: 4.7,
        ratingCount: '5.2k',
        category: 'Productivity',
        description: 'Organize your life with a simple and effective to-do list. Track tasks, filter by status, and stay productive.',
        screenshots: ['https://i.imgur.com/N8yXf4f.png'],
        features: ['Add and complete tasks', 'Filter by status (All, Active, Completed)', 'Clear completed tasks'],
        releaseDate: '01/15/2023',
        lastUpdated: '06/10/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'Users love its clean interface and straightforward functionality for task management.',
        reviewTags: ['Organized', 'Productive', 'Simple'],
    },
    'clock': {
        id: 'clock',
        name: 'Clock',
        icon: <ClockIcon className="w-6 h-6 text-cyan-300" />,
        component: Clock,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.3,
        ratingCount: '980',
        category: 'Utility',
        description: 'Keep track of time with a world clock, stopwatch, and timer, all in one beautifully designed app.',
        screenshots: ['https://i.imgur.com/B7tqj3g.png'],
        features: ['World Clock', 'Stopwatch functionality', 'Countdown Timer'],
        releaseDate: '10/05/2021',
        lastUpdated: '05/01/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A reliable and multi-functional timekeeping application.',
        reviewTags: ['Accurate', 'Multi-functional', 'Useful'],
    },
    'video-audio-player': {
        id: 'video-audio-player',
        name: 'Media Player',
        icon: <VideoFileIcon className="w-6 h-6" />,
        component: VideoAudioPlayer,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 3.9,
        ratingCount: '1.8k',
        category: 'Entertainment',
        description: 'Play your favorite local video and audio files with this simple, built-in media player.',
        screenshots: ['https://i.imgur.com/5d5eL8d.png'],
        features: ['Video playback', 'Audio playback', 'Playback controls'],
        releaseDate: '10/05/2021',
        lastUpdated: '09/12/2023',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'Handles basic media playback well, though some users wish for more features.',
        reviewTags: ['Simple', 'Functional'],
    },
    'pdf-viewer': {
        id: 'pdf-viewer',
        name: 'PDF Viewer',
        icon: <PDFFileIcon className="w-6 h-6" />,
        component: PDFViewer,
        storeCategory: 'app',
        publisher: 'Open Source',
        rating: 4.0,
        ratingCount: '2.1k',
        category: 'Productivity',
        description: 'View and navigate through PDF documents directly within the environment.',
        screenshots: ['https://i.imgur.com/jG5rL9k.png'],
        features: ['PDF rendering', 'Page navigation', 'Zoom functionality'],
        releaseDate: '02/20/2023',
        lastUpdated: '04/25/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A solid choice for viewing PDF files without needing an external application.',
        reviewTags: ['Convenient', 'Readable'],
    },
    'youtube': {
        id: 'youtube',
        name: 'YouTube',
        icon: <YouTubeIcon className="w-6 h-6 text-red-600" />,
        component: Browser,
        baseData: { url: 'https://www.youtube.com/embed' },
        storeCategory: 'app',
        publisher: 'Google',
        rating: 4.9,
        ratingCount: '10M+',
        category: 'Entertainment',
        description: 'Access the world\'s largest video sharing platform. Note: some videos may not play in embedded mode.',
        screenshots: ['https://i.imgur.com/sjwC4t6.png'],
        features: ['Video streaming', 'Content discovery', 'Community interaction'],
        releaseDate: '11/14/2005',
        lastUpdated: '07/01/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'The undisputed king of online video, offering endless entertainment and information.',
        reviewTags: ['Endless Content', 'Community', 'Streaming'],
    },
    'browser': {
        id: 'browser',
        name: 'Edge',
        icon: <EdgeIcon className="w-6 h-6 text-blue-500" />,
        component: Browser,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.4,
        ratingCount: '1.2k',
        category: 'Productivity',
        description: 'A fully functional web browser with tabs, bookmarks, and even developer tools, all inside this web OS.',
        screenshots: ['https://i.imgur.com/pYxRj9R.png'],
        features: ['Tabbed browsing', 'Persistent bookmarks', 'Integrated DevTools', 'Address bar with search'],
        releaseDate: '03/01/2023',
        lastUpdated: '06/28/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'An impressively complete browser simulation with advanced features.',
        reviewTags: ['Full-featured', 'Impressive', 'Developer-friendly'],
    },
    'calculator': {
        id: 'calculator',
        name: 'Calculator',
        icon: <CalculatorIcon className="w-6 h-6 text-gray-300" />,
        component: Calculator,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.7,
        ratingCount: '4.5k',
        category: 'Utility',
        description: 'A simple and classic calculator for all your basic arithmetic needs.',
        screenshots: ['https://i.imgur.com/jQ5gQ2h.png'],
        features: ['Basic arithmetic operations', 'Clear and simple UI', 'Responsive design'],
        releaseDate: '10/05/2021',
        lastUpdated: '08/01/2023',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'It does exactly what it needs to do, perfectly. A reliable and essential tool.',
        reviewTags: ['Reliable', 'Essential', 'Simple'],
    },
    'terminal': {
        id: 'terminal',
        name: 'Terminal',
        icon: <TerminalIcon className="w-6 h-6 text-white" />,
        component: Terminal,
        storeCategory: 'app',
        publisher: 'Open Source',
        rating: 4.9,
        ratingCount: '8.1k',
        category: 'Developer Tools',
        description: 'A simulated command-line interface to interact with the virtual file system using commands like ls, cd, and cat.',
        screenshots: ['https://i.imgur.com/eK7yV1a.png'],
        features: ['File system navigation (ls, cd, pwd)', 'File content viewing (cat)', 'Command history', 'Clear screen command'],
        releaseDate: '04/10/2023',
        lastUpdated: '05/15/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A fantastic tool for developers and those who prefer a command-line workflow.',
        reviewTags: ['Powerful', 'Developer Tool', 'Efficient'],
    },
    'store': {
        id: 'store',
        name: 'Store',
        icon: <StoreIcon className="w-6 h-6 text-green-400" />,
        component: Store,
        storeCategory: 'app',
        publisher: 'Microsoft',
        rating: 4.3,
        ratingCount: '900',
        category: 'Utility',
        description: 'Discover, install, and manage all the apps and games available in this web OS environment.',
        screenshots: ['https://i.imgur.com/n6b3XGj.png'],
        features: ['App and Game discovery', 'Categorized browsing', 'Installation management', 'Search functionality'],
        releaseDate: '05/01/2023',
        lastUpdated: '07/02/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'The central hub for expanding the capabilities of the web OS. Well-designed and easy to navigate.',
        reviewTags: ['Discovery', 'Centralized', 'Organized'],
    },
    'weather': {
        id: 'weather',
        name: 'Weather',
        icon: <WeatherIcon className="w-6 h-6 text-blue-300" />,
        component: Weather,
        storeCategory: 'app',
        publisher: 'Open Source',
        rating: 4.6,
        ratingCount: '3.7k',
        category: 'News & Weather',
        description: 'Get simulated weather updates for major cities around the world with a beautiful, dynamic interface.',
        screenshots: ['https://i.imgur.com/kQ5Z4Z7.png'],
        features: ['Simulated weather for multiple cities', 'Dynamic background gradients', 'Key weather metrics'],
        releaseDate: '06/12/2023',
        lastUpdated: '03/01/2024',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'A visually appealing app for quick weather checks.',
        reviewTags: ['Beautiful UI', 'Informative', 'Simple'],
    },
    'minesweeper': {
        id: 'minesweeper',
        name: 'Minesweeper',
        icon: <MineIcon className="w-6 h-6 text-gray-400" />,
        component: Minesweeper,
        storeCategory: 'game',
        imageUrl: 'https://i.imgur.com/dPVwZqH.png',
        publisher: 'Microsoft',
        rating: 4.9,
        ratingCount: '1M+',
        category: 'Classic Games',
        description: 'The timeless classic. Use logic to clear the board without detonating any mines. A true test of skill and deduction.',
        screenshots: ['https://i.imgur.com/dPVwZqH.png'],
        features: ['Classic gameplay', 'Multiple difficulty levels (simulated)', 'Flagging system', 'Win/Loss detection'],
        releaseDate: '10/01/1990',
        lastUpdated: '01/01/2023',
        systemRequirements: 'This product should work on your device.',
        reviewSummary: 'The perfect recreation of a legendary puzzle game. Infinitely replayable and challenging.',
        reviewTags: ['Classic', 'Challenging', 'Addictive'],
    },
    ...gameDefinitions,
    ...WEB_APP_DEFINITIONS,
};

export const INITIAL_FILE_SYSTEM: FileSystemItem = {
    id: 'root',
    name: 'Home',
    type: 'folder',
    icon: <FolderIcon />,
    content: [
         {
            id: 'desktop',
            name: 'Desktop',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 500000,
            size: 0,
            content: [
                { id: 'desktop-fe', name: 'File Explorer', icon: <FileExplorerIcon className="w-12 h-12 text-yellow-500" />, type: 'app', appId: 'file-explorer', x: 20, y: 20 },
                { id: 'desktop-settings', name: 'Settings', icon: <SettingsIcon className="w-12 h-12 text-gray-400" />, type: 'app', appId: 'settings', x: 20, y: 110 },
                { id: 'desktop-browser', name: 'Edge', icon: <EdgeIcon className="w-12 h-12 text-blue-500" />, type: 'app', appId: 'browser', x: 20, y: 200 },
                { id: 'desktop-notepad', name: 'Notepad', icon: <NotepadIcon className="w-12 h-12 text-white" />, type: 'app', appId: 'notepad', x: 20, y: 290 },
                { id: 'desktop-paint', name: 'Paint', icon: <PaintIcon className="w-12 h-12 text-red-400" />, type: 'app', appId: 'paint', x: 110, y: 20 },
                { id: 'desktop-tm', name: 'Task Manager', icon: <TaskManagerIcon className="w-12 h-12 text-blue-400" />, type: 'app', appId: 'task-manager', x: 110, y: 110 },
                { id: 'desktop-calculator', name: 'Calculator', icon: <CalculatorIcon className="w-12 h-12 text-gray-300" />, type: 'app', appId: 'calculator', x: 110, y: 200 },
                { id: 'desktop-terminal', name: 'Terminal', icon: <TerminalIcon className="w-12 h-12 text-white" />, type: 'app', appId: 'terminal', x: 110, y: 290 },
            ]
        },
        {
            id: 'docs',
            name: 'Documents',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 400000,
            size: 1,
            content: [
                { id: 'doc1', name: 'resume.txt', type: 'file', icon: <TextFileIcon />, content: 'This is my resume.', appId: 'notepad', mimeType: 'text/plain', dateModified: Date.now() - 400000, size: 18 },
                { id: 'doc2', name: 'report.pdf', type: 'file', icon: <PDFFileIcon />, content: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', appId: 'pdf-viewer', mimeType: 'application/pdf', dateModified: Date.now() - 390000, size: 13264 },
            ]
        },
        {
            id: 'pics',
            name: 'Pictures',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 300000,
            size: 2,
            content: [
                { id: 'pic1', name: 'vacation.jpg', type: 'file', icon: <PictureIcon />, content: 'https://picsum.photos/seed/vacation/800/600', appId: 'image-viewer', mimeType: 'image/jpeg', dateModified: Date.now() - 300000, size: 85000 },
                { id: 'pic2', name: 'logo.gif', type: 'file', icon: <PictureIcon />, content: 'https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3Z2cm13MnZjeTIxdTh5bTJic3dmbGJmd2R5bmtwZXdweGwwczV0eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26tn33aiTi1jkl6H6/giphy.gif', appId: 'image-viewer', mimeType: 'image/gif', dateModified: Date.now() - 250000, size: 120000 },
            ]
        },
        {
            id: 'downloads',
            name: 'Downloads',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 200000,
            size: 0,
            content: [],
        },
        {
            id: 'music',
            name: 'Music',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 100000,
            size: 1,
            content: [
                { id: 'music1', name: 'sample.mp3', type: 'file', icon: <AudioFileIcon />, content: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', appId: 'video-audio-player', mimeType: 'audio/mpeg', dateModified: Date.now() - 100000, size: 4400128 },
            ],
        },
        {
            id: 'videos',
            name: 'Videos',
            type: 'folder',
            icon: <FolderIcon />,
            dateModified: Date.now() - 50000,
            size: 1,
            content: [
                 { id: 'video1', name: 'sample.mp4', type: 'file', icon: <VideoFileIcon />, content: 'https://www.w3schools.com/html/mov_bbb.mp4', appId: 'video-audio-player', mimeType: 'video/mp4', dateModified: Date.now() - 50000, size: 941481 },
            ],
        }
    ]
};

export const RECENT_FILES: FileSystemItem[] = [
    { id: 'recent1', name: 'Screen Recording 2025-06-12 0736...', type: 'file', icon: <VideoFileIcon className="w-5 h-5" />, modified: '13m ago', location: 'Videos' },
    { id: 'recent2', name: 'Gmail - Fwd_ 45-Day Learning Sche...', type: 'file', icon: <PDFFileIcon className="w-5 h-5" />, modified: '28m ago', location: 'Documents' },
    { id: 'recent3', name: 'Screenshot (2).png', type: 'file', icon: <PictureIcon className="w-5 h-5"/>, modified: '29m ago', location: 'Pictures/Screenshots' },
    { id: 'recent4', name: 'Screenshot 2025-05-22 155413.png', type: 'file', icon: <PictureIcon className="w-5 h-5"/>, modified: '45m ago', location: 'Pictures' },
    { id: 'recent5', name: 'Screenshot (1).png', type: 'file', icon: <PictureIcon className="w-5 h-5"/>, modified: '56m ago', location: 'Pictures/Screenshots' },
    { id: 'recent6', name: 'Screenshot 2025-06-03 190151.png', type: 'file', icon: <PictureIcon className="w-5 h-5"/>, modified: '1h ago', location: 'Pictures' },
];
